sources:
  - name: guild-subgraph
    handler:
      graphql:
        endpoint: ${DXGOV_GUILD_GRAPHQL_ENDPOINT}
  - name: dao-subgraph
    handler:
      graphql:
        endpoint: ${DXGOV_DAO_GRAPHQL_ENDPOINT}
documents:
  - './src/**/*.graphql'

