sources:
  - name: guild-subgraph
    handler:
      graphql:
        endpoint: ${DXGOV_GUILD_GRAPHQL_ENDPOINT}
  - name: 1-5-subgraph
    handler:
      graphql:
        endpoint: ${DXGOV_1-5_GRAPHQL_ENDPOINT}
documents:
  - './src/**/*.graphql'
