sources:
  - name: dxgov-guild-subgraph
    handler:
      graphql:
        endpoint: http://127.0.0.1:8000/subgraphs/name/dxdao/guilds
        # endpoint: https://api.thegraph.com/subgraphs/name/dxgovernance/guild-subgraph-gnosis
documents:
  - './src/**/*.graphql'
