name: Jest Tests
on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build local config
        run: cd apps/davi & node scripts/beforeBuild.js

      - name: Build local bytecodes
        run: cd apps/davi & node scripts/updateBytecodes.js

      - name: Run Jests Test
        run: pnpm run test

      








