name: Tests & Format Check
on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - name: Inject workflow information
        uses: potiuk/get-workflow-origin@v1_3
        id: workflow-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          set-safe-directory: false

      - name: Cloning contracts
        run: git clone -b v2.0 https://github.com/DXgovernance/dxdao-contracts packages/dxdao-contracts && git submodule sync packages/dxdao-contracts
        # TODO: Replace v2.0 to develop after https://github.com/DXgovernance/dxdao-contracts/pull/277 is merged

      - name: Pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build local config
        run: node apps/davi/scripts/beforeBuild.js

      - name: Run Jests Test
        run: pnpm run test --force

      - name: Run code format check
        run: pnpm run format-check
